version : "3"

services:
    server:
        container_name : server
        restart: always
        build: .
        ports:
        - '9000:5000'
        links:
        - mongo

    mongo:
          container_name: mongo
          image : mongo
          ports:
          - '27017:27017'
